In [2]:
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import time
import pandas as pd
import h5py
import os
from sklearn.preprocessing import LabelEncoder
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

from sklearn.svm import LinearSVC

from sklearn.svm import SVC

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from IPython.display import Image, display_png
#import pydotplus as pdp

from sklearn.ensemble import RandomForestClassifier

import seaborn as sns

/usr/local/pyenv/versions/3.6.5/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [4]:
import xgboost as xgb

ModuleNotFoundError: No module named 'xgboost'

In [2]:
dic_type={}
dic_type[1]="str"
dic_type[2]="str"
for i in range(3,11691):
    dic_type[2]="float64"

In [7]:
ft2=pd.read_table("GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_tpm.gct/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_tpm.gct", sep="\t", header=2,dtype=dic_type)

In [8]:
ft1=ft2.transpose()

In [9]:
ft1_new = ft1.drop("Description", axis=0).drop("Name", axis=0)

In [5]:
df2=pd.read_csv("answer.csv", delimiter="\t")

In [10]:
merge=pd.merge(df2, ft1,left_on="SAMPID",right_index=True)

In [11]:
df3=merge.iloc[:,:2]

In [12]:
ft3=merge[:].drop("SMTS", axis=1)

In [13]:
label = LabelEncoder()
#ラベルを覚えさせる
label = label.fit(df3['SMTS'])
#ラベルを整数に変換
df3['tissue'] = label.transform(df3['SMTS'])
df3.head()

SAMPID            SMTS  tissue
3  GTEX-1117F-0226-SM-5GZZ7  Adipose Tissue       0
4  GTEX-1117F-0426-SM-5EGHI          Muscle      15
5  GTEX-1117F-0526-SM-5EGHJ    Blood Vessel       4
6  GTEX-1117F-0626-SM-5N9CS    Blood Vessel       4
7  GTEX-1117F-0726-SM-5GIEN           Heart      11

In [14]:
X_train, X_test, y_train, y_test =train_test_split(ft3.iloc[:,1:],df3.iloc[:,2])
print(ft3.shape,X_train.shape,y_train.shape)
print(ft3.shape,X_train.shape,y_train.shape)

(11688, 56203) (8766, 56202) (8766,)
(11688, 56203) (8766, 56202) (8766,)


In [13]:
print(ft3.shape,X_train.shape,y_train.shape)

(11688, 56203) (8766, 56202) (8766,)


In [14]:
print(ft3.shape,X_train.shape,y_train.shape)

(11688, 3) (2922, 56202) (2922,)


In [57]:
clf_lr = LogisticRegression(solver='lbfgs', C=1,  multi_class= "auto", max_iter=1000)#モデルの生成
clf_lr.fit(X_train, y_train)#モデルの生成
lr_p= clf_lr.predict(X_test)#テストデータに伴う予測値
ac_score_lr = metrics.accuracy_score(y_test, lr_p)
print(ac_score_lr)

/Users/tsunodaut03/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.9828884325804244


In [18]:
df3.head()

SAMPID            SMTS  tissue
3  GTEX-1117F-0226-SM-5GZZ7  Adipose Tissue       0
4  GTEX-1117F-0426-SM-5EGHI          Muscle      15
5  GTEX-1117F-0526-SM-5EGHJ    Blood Vessel       4
6  GTEX-1117F-0626-SM-5N9CS    Blood Vessel       4
7  GTEX-1117F-0726-SM-5GIEN           Heart      11

In [28]:
ft3.head()

SAMPID        0      1       2        3  4        5  \
3  GTEX-1117F-0226-SM-5GZZ7   0.1082   21.4  0.1602  0.05045  0        0   
4  GTEX-1117F-0426-SM-5EGHI  0.08177  15.03       0        0  0  0.04947   
5  GTEX-1117F-0526-SM-5EGHJ        0  17.53       0  0.05547  0        0   
6  GTEX-1117F-0626-SM-5N9CS        0  23.82       0        0  0        0   
7  GTEX-1117F-0726-SM-5GIEN  0.02271  7.443  0.1514  0.03179  0        0   

         6        7        8   ...    56192   56193 56194   56195  56196  \
3        0   0.2392   0.1869   ...    12260       0     0       0   2894   
4   0.1013  0.06782   0.1413   ...    33640       0     0       0  10280   
5  0.07366   0.1972   0.1121   ...    13690    0.98     0       0   4429   
6        0  0.02808  0.04789   ...    11830       0     0       0   1220   
7  0.04221  0.07535   0.1606   ...    69160  0.5616     0  0.5458   7759   

   56197  56198  56199   56200   56201  
3   3754  16.04   6856  0.9319       0  
4  14580  43.81  26010   6.341   6.155  
5   6665  23.52   8377   1.025  0.9944  
6  806.3      0   8681       0       0  
7   7031  2.246  29090       0    1.14  

[5 rows x 56203 columns]

In [25]:
print(df3.iloc[:,2].values)

[ 0 15  4 ...  4 15  0]


In [24]:
df4=np.identity(30)[df3.iloc[:,2].values]

In [26]:
print(df4)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [30]:
ft4=ft3.iloc[:,1:].values.astype(np.float64)

In [31]:
print(ft4)

[[1.082e-01 2.140e+01 1.602e-01 ... 6.856e+03 9.319e-01 0.000e+00]
 [8.177e-02 1.503e+01 0.000e+00 ... 2.601e+04 6.341e+00 6.155e+00]
 [0.000e+00 1.753e+01 0.000e+00 ... 8.377e+03 1.025e+00 9.944e-01]
 ...
 [7.797e-02 1.035e+01 0.000e+00 ... 1.885e+04 0.000e+00 2.608e+00]
 [1.181e-01 6.260e+00 1.312e-01 ... 3.624e+04 4.731e+01 4.444e+00]
 [0.000e+00 7.699e+00 0.000e+00 ... 2.752e+04 3.277e+00 6.362e-01]]


In [33]:
ft4.shape

(11688, 56202)

In [34]:
df4.shape

(11688, 30)

In [84]:
#np.save("train.npy",ft4)
#np.save("test.npy",df4)

In [3]:
ft4=np.load("train.npy")
df4=np.load("test.npy")

In [4]:
X_train, X_test, y_train, y_test =train_test_split(ft4,df4)
#print(ft3.shape,X_train.shape,y_train.shape)
#print(ft3.shape,X_train.shape,y_train.shape)

In [56]:
import math
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import tensorflow as tf
is_training = tf.placeholder(tf.bool)
tf.reset_default_graph() # グラフのリセット


x = tf.placeholder(tf.float32, [None, 56202])
t = tf.placeholder(tf.float32, [None, 30])

class Dense:
    def __init__(self, in_dim, out_dim, function=lambda x: x):
        self.W = tf.Variable(tf.random_uniform(shape=(in_dim, out_dim), minval=-0.08, maxval=0.08), name='W')
        self.b = tf.Variable(tf.zeros(out_dim), name='b')
        self.function = function
        
        self.params = [self.W, self.b]
    
    def __call__(self, x):
        return self.function(tf.matmul(x, self.W) + self.b)

def sgd(cost, params, eps=0.1):
    grads = tf.gradients(cost, params)
    updates = []
    for param, grad in zip(params, grads):
        updates.append(param.assign_sub(eta * grad))
    return updates

def tf_log(x):
    return tf.log(tf.clip_by_value(x, 1e-10, x))
dropout_keep_prob = 0.5
class Dropout:
    def __init__(self, dropout_keep_prob=1.0):
        self.dropout_keep_prob = dropout_keep_prob
        self.params = []
    
    def __call__(self, x):
        # 訓練時のみdropoutを適用
        return tf.cond(
            pred=is_training,
            true_fn=lambda: tf.nn.dropout(x, keep_prob=self.dropout_keep_prob),
            false_fn=lambda: x
        )

layers = [
    Dense(56202, 200, tf.nn.relu),
    Dropout(dropout_keep_prob),
    Dense(200, 200, tf.nn.relu),
    Dropout(dropout_keep_prob),
    Dense(200, 30, tf.nn.softmax)
]

params = []
h = x
for layer in layers:
    h = layer(h)
    params += layer.params
y = h

cost = - tf.reduce_mean(tf.reduce_sum(t * tf.log(y) + (1 - t) * tf.log(1 - y), axis=1))

updates = sgd(cost, params)
train = tf.group(*updates)

n_epochs = 1
batch_size = 100
n_batches = math.ceil(len(X_train) / batch_size)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for epoch in range(n_epochs):
    X_train, y_train = shuffle(X_train, y_train)
    for i in range(n_batches):
        start = i * batch_size
        end = start + batch_size
        sess.run(train, feed_dict={x: x_train[start:end], t: t_train[start:end], is_training: True})
        y_pred, cost_valid_ = sess.run([y, cost], feed_dict={x: x_valid, t: t_valid, is_training: False})
        print('EPOCH: {}, Valid Cost: {:.3f}, Valid Accuracy: {:.3f}'.format(
            epoch + 1,
            cost_valid_,
            accuracy_score(t_valid.argmax(axis=1), y_pred.argmax(axis=1))
        ))

%y_pred = # WRITE ME

submission = pd.Series(y_pred, name='label')
submission.to_csv('/root/userspace/public/chap04/materials/submission_pred.csv', header=True, index_label='id')

ValueError: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout/mul:0", shape=(?, 200), dtype=float32).

In [90]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 14903423165865420992, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 183762944
 locality {
   bus_id: 1
 }
 incarnation: 5849906992134713495
 physical_device_desc: "device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1", name: "/device:GPU:1"
 device_type: "GPU"
 memory_limit: 335937536
 locality {
   bus_id: 1
 }
 incarnation: 7538597709286145337
 physical_device_desc: "device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1", name: "/device:GPU:2"
 device_type: "GPU"
 memory_limit: 335937536
 locality {
   bus_id: 1
 }
 incarnation: 16742161398150538941
 physical_device_desc: "device: 2, name: GeForce GTX 1080 Ti, pci bus id: 0000:09:00.0, compute capability: 6.1", name: "/device:GPU:3"
 device_type: "GPU"
 memory_limit: 335937536
 locality {
   bus_id: 1
 }
 incarnation: 9968965488133635333
 physical_device_desc:

In [6]:
from keras.models import Sequential
from keras.layers import Dense,Activation
X_train,X_valid=np.split(X_train,[6000])
y_train,y_valid=np.split(y_train,[6000])
model1=Sequential()
model1.add(Dense(2048,activation="relu",input_shape=(56202,)))
model1.add(Dense(30,activation="relu"))
model1.add(Activation("sigmoid"))
model1.compile(loss="binary_crossentropy",optimizer="rmsprop",metrics=["accuracy"])
fit=model1.fit(X_train,y_train,epochs=10,batch_size=1028,verbose=2,validation_split=0.9,validation_data=(X_valid,y_valid),callbacks=[])
score=model1.evaluate(X_test,y_test,batch_size=64)

Train on 6000 samples, validate on 0 samples
Epoch 1/10
 - 2s - loss: 1.9328 - acc: 0.8871
Epoch 2/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 3/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 4/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 5/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 6/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 7/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 8/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 9/10
 - 2s - loss: 0.6948 - acc: 0.9666
Epoch 10/10
 - 2s - loss: 0.6948 - acc: 0.9666
2922/2922 [==============================] - 1s 263us/step


In [82]:
import sys
print("{}{:>25}{:>10}{}".format('|','valuable name','|','memory','|'))
print("-------")
for var in dir():
    if not var.startswith("_") and sys.getsizeof(eval(var))>10000:
        print("{}{:>25}{:>10}{}".format('|',var,'|',sys.getsizeof(eval(var)),'|'))

|            valuable name         |memory
-------
|                   X_test         |1313778064
|                      df2         |2257242
|                      df3         |1884123
|                      df4         |2805232
|                      ft4         |5255111920
|                   y_test         |701392


In [75]:
del ft3

In [46]:
del ft1_new

In [49]:
del merge

In [ ]:
2046